import { Injectable } from '@angular/core';

export type Role = 'ADMIN' | 'CUSTOMER';
export type OrderStatus = 'PENDING' | 'CONFIRMED' | 'PACKED' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED';
export interface User { id:number; name:string; email:string; password:string; role:Role; phone:string; address:string; }
export interface Product { id:number; category:string; name:string; description:string; price:number; gst:number; stock:number; sku:string; active:boolean; }
export interface OrderItem { productId:number; name:string; qty:number; price:number; gst:number; total:number; }
export interface Order { id:number; orderNo:string; customer:string; customerEmail:string; address:string; status:OrderStatus; items:OrderItem[]; subtotal:number; gstAmount:number; total:number; deliveryPartner:string; trackingNo:string; expectedDate:string; createdAt:string; }
export interface Issue { id:number; customer:string; customerEmail:string; subject:string; message:string; status:'OPEN'|'IN_PROGRESS'|'RESOLVED'; reply:string; }
export interface CartItem { productId:number; qty:number; }
export interface AppState { users:User[]; products:Product[]; orders:Order[]; issues:Issue[]; cart:Record<string,CartItem[]>; }

const rupee = new Intl.NumberFormat('en-IN');
const catalog: Record<string, string[]> = {
  'Flagship Smartphones': ['Apple iPhone 16 Pro Max','Apple iPhone 16 Pro','Samsung Galaxy S25 Ultra','Samsung Galaxy S25+','Google Pixel 10 Pro XL','Google Pixel 10 Pro','OnePlus 13','Xiaomi 15 Ultra','Xiaomi 15 Pro','vivo X200 Ultra','vivo X200 Pro','OPPO Find X8 Ultra','OPPO Find X8 Pro','HONOR Magic7 Pro','Huawei Pura 80 Ultra','ASUS ROG Phone 9 Pro','Sony Xperia 1 VII','Nothing Phone (3)','Motorola Edge 60 Ultra','RedMagic 10 Pro'],
  'Laptops': ['Apple MacBook Air M4 (13-inch)','Apple MacBook Air M4 (15-inch)','Apple MacBook Pro 14 (M4 Pro)','Apple MacBook Pro 16 (M4 Max)','Dell XPS 13','Dell XPS 16','HP Spectre x360 14','HP Omen Max 16','Lenovo Yoga Pro 9i','Lenovo ThinkPad X1 Carbon Gen 13','Lenovo Legion Pro 7i','ASUS Zenbook S 16','ASUS ROG Zephyrus G16','ASUS ROG Strix Scar 18','Acer Swift Go 14','Acer Predator Helios Neo 16','MSI Stealth 18 AI Studio','MSI Titan 18 HX AI','Microsoft Surface Laptop 7','Samsung Galaxy Book5 Pro 360'],
  'Monitors': ['Dell UltraSharp U2725QE','Dell Alienware AW3225QF','LG UltraFine 5K','LG UltraGear 32GS95UE','Samsung Odyssey OLED G8','Samsung ViewFinity S9','ASUS ProArt PA32UCXR','ASUS ROG Swift PG32UCDM','BenQ PD3225U','BenQ MOBIUZ EX321UX','Gigabyte M32U','Gigabyte FO32U2P','MSI MPG 321URX QD-OLED','Acer Predator X32','Acer Nitro XV275K','Philips Evnia 49M2C8900','ViewSonic ColorPro VP2788-5K','HP Omen Transcend 32','Lenovo ThinkVision P32pz-30','Apple Studio Display'],
  // 'Headphones': ['Sony WH-1000XM6','Sony WH-1000XM5','Bose QuietComfort Ultra','Bose QuietComfort','Apple AirPods Max','Sennheiser Momentum 4 Wireless','Sonos Ace','Bowers & Wilkins Px8','Bowers & Wilkins Px7 S2e','JBL Tour One M3','JBL Live 770NC','Marshall Monitor III ANC','Skullcandy Crusher ANC 2','Audio-Technica ATH-M50xBT2','Shure AONIC 50 Gen 2','Bang & Olufsen Beoplay HX','Dyson OnTrac','Focal Bathys','Edifier WH950NB','Anker Soundcore Space One Pro'],
  'Bluetooth Earbuds': ['Apple AirPods Pro (2nd Gen)','Samsung Galaxy Buds3 Pro','Sony WF-1000XM5','Bose QuietComfort Ultra Earbuds','Google Pixel Buds Pro 2','OnePlus Buds Pro 3','Nothing Ear','Nothing Ear (a)','JBL Tour Pro 3','Sennheiser Momentum True Wireless 4','Beats Fit Pro','Beats Studio Buds+','Jabra Elite 10 Gen 2'],
  'Smartwatches': ['Apple Watch Ultra 2','Apple Watch Series 10','Samsung Galaxy Watch Ultra','Samsung Galaxy Watch8 Classic','Google Pixel Watch 3','Garmin Fenix 8','Garmin Venu 3','Huawei Watch GT 5 Pro','OnePlus Watch 3','Xiaomi Watch S4','Amazfit Balance 2','Amazfit T-Rex 3','COROS Pace Pro','Suunto Race S','Fitbit Sense 2','Nothing CMF Watch Pro 2','OPPO Watch X2','HONOR Watch 5 Ultra'],
  "Men's Fashion Brands": ['H&M','Zara','UNIQLO','GUCCI','Louis Vuitton (LV)','Versace','Prada','Dior','Balenciaga','Burberry','Armani (Emporio Giorgio Armani)','Dolce & Gabbana','Hugo Boss','Ralph Lauren','Tommy Hilfiger','Calvin Klein','Lacoste','Diesel','Off-White','AMI Paris'],
  "Men's Shirts": ['H&M Premium Cotton Shirt','H&M Linen Blend Shirt','Zara Textured Overshirt','Zara Oxford Shirt','UNIQLO Oxford Button-Down Shirt','UNIQLO Premium Linen Shirt','Ralph Lauren Custom Fit Oxford Shirt','Tommy Hilfiger Regular Fit Oxford Shirt','Calvin Klein Slim Fit Dress Shirt','Lacoste Classic Fit Cotton Shirt','Hugo Boss P-Hank Kent Shirt'],
  "Men's Jeans": ["Levi's 511 Slim Fit","Levi's 501 Original","Levi's 512 Slim Taper",'Diesel D-Strukt','Diesel 1979 Sleenker','Calvin Klein Slim Jeans','Tommy Hilfiger Bleecker Jeans','Armani Exchange Slim Jeans','Zara Slim Fit Jeans','H&M Skinny Fit Jeans','UNIQLO Selvedge Stretch Jeans','GUCCI Straight Denim Jeans',],
  // 'T-Shirts': ['H&M Premium Cotton T-Shirt','Zara Heavyweight T-Shirt','UNIQLO AIRism Tee','UNIQLO U Crew Neck Tee','Calvin Klein Logo Tee','Tommy Hilfiger Essential Tee','Lacoste Classic Pique Tee','Ralph Lauren Polo Bear Tee','Armani Exchange Logo Tee','Diesel T-Diegor Tee','Hugo Boss Tee 3','Gucci GG Logo T-Shirt','Louis Vuitton Embroidered T-Shirt','Versace Medusa T-Shirt','Dior CD Icon Tee','Prada Triangle Logo Tee','Balenciaga Political Campaign Tee','Off-White Arrow Tee','Burberry EKD Logo Tee','AMI Paris Ami de Coeur Tee'],
  // 'Sneakers': ["Nike Air Force 1 '07",'Nike Air Jordan 1 High','Adidas Samba OG','Adidas Gazelle','New Balance 9060','New Balance 990v6','Puma Palermo','ASICS GEL-Kayano 14','Converse Chuck Taylor 70','Vans Old Skool','Gucci Ace Sneakers','Louis Vuitton Trainer','Dior B27',"Prada America's Cup",'Balenciaga Triple S','Balenciaga Track','Alexander McQueen Oversized Sneaker','Golden Goose Super-Star','On Cloudmonster 2','HOKA Clifton 10'],
  // 'Jackets': ['Zara Bomber Jacket','H&M Varsity Jacket','UNIQLO Ultra Light Down Jacket',"Levi's Trucker Jacket",'Tommy Hilfiger Bomber Jacket','Ralph Lauren Quilted Jacket','Calvin Klein Puffer Jacket','Hugo Boss Leather Jacket','Armani Exchange Bomber','Diesel Biker Jacket','GUCCI GG Canvas Jacket','Louis Vuitton Monogram Jacket','Versace Barocco Bomber','Prada Re-Nylon Jacket','Dior Oblique Jacket','Burberry Harrington Jacket','Balenciaga Oversized Bomber','Off-White Varsity Jacket','Moncler Maya Down Jacket','Stone Island Soft Shell Jacket']
};
const basePrices: Record<string, number> = { 'Flagship Smartphones': 79999, Laptops: 94999, Monitors: 27999, Headphones: 9999, 'Bluetooth Earbuds': 4999, Smartwatches: 12999, "Men's Fashion Brands": 2999, "Men's Shirts": 2499, "Men's Jeans": 3499, 'T-Shirts': 1499, Sneakers: 5999, Jackets: 7999 };

@Injectable({ providedIn:'root' })
export class StoreService {
  private key = 'quickmart_oms_state_v1';
  state: AppState = this.load();
  format(n:number) { return '₹' + rupee.format(Math.round(n)); }
  currentUser() { const raw = localStorage.getItem('quickmart_user'); return raw ? JSON.parse(raw) as User : null; }
  isAdmin() { return this.currentUser()?.role === 'ADMIN'; }
  logout() { localStorage.removeItem('quickmart_user'); }
  login(email:string, password:string) { const user = this.state.users.find((u:User) => u.email.toLowerCase() === email.toLowerCase() && u.password === password); if (!user) return null; localStorage.setItem('quickmart_user', JSON.stringify(user)); return user; }
  register(data: Partial<User>) { const user: User = { id:Date.now(), name:data.name || 'New Customer', email:data.email || '', password:data.password || 'customer123', role:'CUSTOMER', phone:data.phone || '', address:data.address || 'Bhubaneswar, Odisha' }; this.state.users.push(user); this.save(); localStorage.setItem('quickmart_user', JSON.stringify(user)); return user; }
  visibleOrders() { const u=this.currentUser(); return this.isAdmin() ? this.state.orders : this.state.orders.filter((o:Order)=>o.customerEmail===u?.email); }
  cartItems() { const u=this.currentUser(); const rows=(u ? this.state.cart[u.email] || [] : []); return rows.map((item:CartItem)=>({ ...item, product:this.state.products.find((p:Product)=>p.id===item.productId) })).filter((x:any)=>x.product); }
  cartCount() { return this.cartItems().reduce((s:number,i:any)=>s+i.qty,0); }
  addToCart(productId:number, qty:number) { const u=this.currentUser(); const p=this.state.products.find((x:Product)=>x.id===productId); if(!u || !p || qty<1) return false; this.state.cart[u.email] ||= []; const found=this.state.cart[u.email].find((x:CartItem)=>x.productId===productId); if(found) found.qty += qty; else this.state.cart[u.email].push({productId, qty}); this.save(); return true; }
  removeFromCart(productId:number) { const u=this.currentUser(); if(!u) return; this.state.cart[u.email]=(this.state.cart[u.email]||[]).filter((x:CartItem)=>x.productId!==productId); this.save(); }
  updateCart(productId:number, qty:number) { const u=this.currentUser(); const item=u ? (this.state.cart[u.email]||[]).find((x:CartItem)=>x.productId===productId) : null; if(item){ item.qty=Math.max(1,Number(qty)); this.save(); } }
  visibleIssues() { const u=this.currentUser(); return this.isAdmin() ? this.state.issues : this.state.issues.filter((i:Issue)=>i.customerEmail===u?.email); }
  metrics() { const revenue = this.state.orders.reduce((s:number,o:Order)=>s+o.total,0); return { products:this.state.products.length, orders:this.state.orders.length, revenue, customers:this.state.users.filter((u:User)=>u.role==='CUSTOMER').length, lowStock:this.state.products.filter((p:Product)=>p.stock<20).length }; }
  addProduct(p: Partial<Product>) { const product: Product = { id:Date.now(), category:p.category || 'General', name:p.name || 'New Product', description:p.description || 'Product description', price:Number(p.price || 0), gst:Number(p.gst || 18), stock:Number(p.stock || 0), sku:p.sku || 'QM-' + Date.now(), active:true }; this.state.products.unshift(product); this.save(); return product; }
  adjustStock(productId:number, qty:number) { const p=this.state.products.find((x:Product)=>x.id===productId); if (p) { p.stock = Math.max(0, p.stock + qty); this.save(); } }
  checkoutCart() {
    const u=this.currentUser(); const cart=this.cartItems(); if(!u || cart.length===0) return null;
    const items: OrderItem[] = []; let subtotal=0; let gstAmount=0;
    for (const row of cart as any[]) {
      const p = row.product as Product; if (p.stock < row.qty) return null;
      const line = p.price * row.qty; const gst = line * p.gst / 100; p.stock -= row.qty;
      subtotal += line; gstAmount += gst; items.push({ productId:p.id, name:p.name, qty:row.qty, price:p.price, gst:p.gst, total:line+gst });
    }
    const order: Order = { id:Date.now(), orderNo:'QM-ORD-' + String(this.state.orders.length + 1001), customer:u.name, customerEmail:u.email, address:u.address, status:'PENDING', items, subtotal, gstAmount, total:subtotal+gstAmount, deliveryPartner:'Not assigned', trackingNo:'Pending', expectedDate:'', createdAt:new Date().toLocaleDateString('en-IN') };
    this.state.orders.unshift(order); this.state.cart[u.email]=[]; this.save(); return order;
  }
  updateOrder(id:number, status:OrderStatus) { const o=this.state.orders.find((x:Order)=>x.id===id); if (o && this.isAdmin()) { o.status=status; this.save(); } }
  updateDelivery(id:number, partner:string, tracking:string, expected:string) { const o=this.state.orders.find((x:Order)=>x.id===id); if (o && this.isAdmin()) { o.deliveryPartner=partner; o.trackingNo=tracking; o.expectedDate=expected; o.status='OUT_FOR_DELIVERY'; this.save(); } }
  raiseIssue(subject:string, message:string) { const u=this.currentUser(); if (!u) return; this.state.issues.unshift({ id:Date.now(), customer:u.name, customerEmail:u.email, subject, message, status:'OPEN', reply:'' }); this.save(); }
  replyIssue(id:number, reply:string) { const i=this.state.issues.find((x:Issue)=>x.id===id); if (i && this.isAdmin()) { i.reply=reply; i.status='RESOLVED'; this.save(); } }
  save() { localStorage.setItem(this.key, JSON.stringify(this.state)); }
  private makeProducts(): Product[] { let id=100; return Object.entries(catalog).flatMap(([category,names]) => names.slice(0,10).map((name, i) => ({ id:++id, category, name, description: category.includes('Fashion') ? 'Premium menswear brand available for booking' : category.includes('Shirts') || category.includes('Jeans') || category.includes('T-Shirts') || category.includes('Sneakers') || category.includes('Jackets') ? 'Men\'s fashion product with GST invoice' : 'Latest original product with warranty and GST invoice', price: (basePrices[category] || 1999) + (i * (category.includes('Smartphones') || category==='Laptops' ? 2500 : 350)), gst: category.includes('Fashion') || category.includes('Shirts') || category.includes('Jeans') || category.includes('T-Shirts') ? 5 : 18, stock: 25 + ((i * 7) % 90), sku: 'QM-' + category.replace(/[^A-Z0-9]/gi,'').slice(0,4).toUpperCase() + '-' + id, active:true }))); }
  private load(): AppState { const raw = localStorage.getItem(this.key); if (raw) { try { const parsed = JSON.parse(raw) as AppState; parsed.users ||= []; parsed.products ||= this.makeProducts(); parsed.orders ||= []; parsed.issues ||= []; parsed.cart ||= {}; return parsed; } catch { localStorage.removeItem(this.key); } } const products=this.makeProducts(); return { users:[{ id:1, name:'Admin User', email:'admin@quickmart.com', password:'admin123', role:'ADMIN', phone:'9999999999', address:'QuickMart Head Office, Bhubaneswar, Odisha' },{ id:2, name:'Demo Customer', email:'customer@quickmart.com', password:'customer123', role:'CUSTOMER', phone:'8888888888', address:'Station Square, Bhubaneswar, Odisha' }], products, cart:{}, orders:[{ id:201, orderNo:'QM-ORD-1001', customer:'Demo Customer', customerEmail:'customer@quickmart.com', address:'Station Square, Bhubaneswar, Odisha', status:'PACKED', items:[{productId:101,name:products[0].name,qty:1,price:products[0].price,gst:products[0].gst,total:products[0].price*1.18}], subtotal:products[0].price, gstAmount:products[0].price*.18, total:products[0].price*1.18, deliveryPartner:'Delhivery', trackingNo:'DLV-QM1001', expectedDate:'14/07/2026', createdAt:'10/07/2026' }], issues:[{ id:301, customer:'Demo Customer', customerEmail:'customer@quickmart.com', subject:'Need invoice copy', message:'Please provide invoice for my latest order.', status:'OPEN', reply:'' }] }; }
}
